// #define LUA_INT_DEFAULT     LUA_INT_INT
#define LUA_INT_DEFAULT     LUA_INT_LONGLONG
// #define LUA_FLOAT_DEFAULT   LUA_FLOAT_FLOAT
#define LUA_FLOAT_DEFAULT   LUA_FLOAT_DOUBLE

#define LUA_PATH_DEFAULT ""
#define LUA_CPATH_DEFAULT ""

#define LUA_NOCVTN2S
#define LUA_NOCVTS2N

@LUACONF@

#undef LUAI_MAXSTACK
#define LUAI_MAXSTACK       1000
