#!/bin/bash
# Copyright 2023 Remy Blank <remy@c-space.org>
# SPDX-License-Identifier: MIT

set -o errexit -o pipefail -o nounset

if [[ $# != 1 ]]; then
    echo "Usage: $(basename "$0") DEVICE" >&2
    exit 2
fi

trap "echo -ne $'\e[?25h'" EXIT  # Show the cursor on termination
socat READLINE "OPEN:$1,b115200,icanon=0,time=5,ignbrk,brkint=0,icrnl=0,imaxbel=0,opost=0,onlcr=0,isig=0,iexten=0,echo=0,echoe=0,echok=0,echoctl=0,echoke=0,iexten=0,hupcl=0,ixon=0"
